### ISSUE TITLE
Add some features

### ISSUE THREAD

**Issue by Ionys320** [torbenkeller/expandable_bottom_sheet#1]
Hello,
Could you add the possibility to click on the persistent header to open the bottom sheet ? And also, could you create an option to not allow the possibility of partially opening the bottom sheet ?

Thanks a lot !

**Comment by torbenkeller** [comment]
It's planned to let you call a open or close function and get actual status. So if this is implemmented you can use a `GestureDetector` in your `persistentHeader` and open the sheet on tap.

**Comment by Ionys320** [comment]
Yep, okay!

**Comment by vincepunkrock** [comment]
@torbenkeller I'd also be interested in this feature. Is the implementation still planned? Thanks
