### ISSUE TITLE
question - swipe to close

### ISSUE THREAD

**Issue by stellanhaglund** [torbenkeller/expandable_bottom_sheet#10]
Hello, I was just testing the expert example and I was wondering if there is any swipe to close functionality?

**Comment by torbenkeller** [comment]
Yes there is swipe to close functionality

**Comment by Myzel394** [comment]
> Yes there is swipe to close functionality

How? It's not helpful by simply saying it exists without giving any further details. There is no mention of it in the docs, how would you add it?
