### ISSUE TITLE
onIsExtendedCallback() and onIsContractedCallback() is not called when toggled.

### ISSUE THREAD

**Issue by youngtaekoh** [torbenkeller/expandable_bottom_sheet#11]
Hi, thank you for your great work.

When a user enables `enableToggle` and extends or contracts the content by means of toggling, callback functions are not called.

Adding `_callCallbacks = true;` to `raw_expandable_bottom_sheet.dart:285` seems to solve this problem

```
void _toggle() {
  if (widget.enableToggle) {
    _callCallbacks = true;
    if (expansionStatus == ExpansionStatus.expanded) {
      _animateToBottom();
    }
    if (expansionStatus == ExpansionStatus.contracted) {
      _animateToTop();
    }
  }
}
```

**Comment by torbenkeller** [comment]
Thank you for reporting that bug!

i will fix it in the next release!
