### ISSUE TITLE
WidgetsBinding.instance no longer needs null-aware operator

### ISSUE THREAD

**Issue by Devenom1** [torbenkeller/expandable_bottom_sheet#22]
This is the warning we get when building our apps with this library

> ../../development/flutter/.pub-cache/hosted/pub.dartlang.org/expandable_bottom_sheet-1.1.1+1/lib/src/raw_expandable_bottom_sheet.dart:160:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
>  - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../development/flutter/packages/flutter/lib/src/widgets/binding.dart').
>     WidgetsBinding.instance!

It's not a major issue or anything but it's the only warning we get while building apps with this library.

Could the null aware operator be removed?

**Comment by torbenkeller** [comment]
Thanks for the PR!
