### ISSUE TITLE
Bottom sheet animates to max when keyboard is shown

### ISSUE THREAD

**Issue by MrAlek** [torbenkeller/expandable_bottom_sheet#5]
First of all, thanks for a great library @torbenkeller!

We're experiencing an issue where the expandable bottom sheet animates to max whenever the keyboard is shown and peeks up above the keyboard. Also, it stays maxed out when the keyboard is dismissed. We would like the sheet to stay hidden behind the keyboard.

Looking at the stack trace, it seems like the sheet thinks it's been dragged out of bounds and thus animates to the closes state which is the max state.

![image](https://user-images.githubusercontent.com/1496135/95768684-00fc1100-0cb7-11eb-87f6-f10ab68f6492.png)

![RPReplay_Final1602519562](https://user-images.githubusercontent.com/1496135/95769101-a6af8000-0cb7-11eb-90c3-8216303deb38.gif)

**Comment by torbenkeller** [comment]
When you are using a Scaffold, you can try to  use `resizeToAvoidBottomInset = false`. Does this help?

**Comment by MrAlek** [comment]
@torbenkeller It did and I feel very stupid now. Very weird that this is a standard behavior in Flutter. Thanks for the help.
